[project]
name = "ai-service-center"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10.13"
dependencies = [
    "absl-py==2.3.0",
    "accelerate==0.16.0",
    "aiohappyeyeballs==2.6.1",
    "aiohttp==3.12.13",
    "aiohttp-cors==0.8.1",
    "aiosignal==1.3.2",
    "albumentations==1.3.1",
    "ansicon==1.89.0",
    "antlr4-python3-runtime==4.9.3",
    "anyio==4.9.0",
    "asttokens==3.0.0",
    "async-timeout==5.0.1",
    "asyncmy==0.2.10",
    "attrs==25.3.0",
    "autogluon==0.8.2",
    "autogluon-common==0.8.2",
    "autogluon-core==0.8.2",
    "autogluon-features==0.8.2",
    "autogluon-multimodal==0.8.2",
    "autogluon-tabular==0.8.2",
    "autogluon-timeseries==0.8.2",
    "beautifulsoup4==4.13.4",
    "blessed==1.21.0",
    "blis==1.2.1",
    "boto3==1.38.38",
    "botocore==1.38.38",
    "cachetools==5.5.2",
    "catalogue==2.0.10",
    "catboost==1.1.1",
    "certifi==2025.6.15",
    "charset-normalizer==3.4.2",
    "click==8.2.1",
    "cloudpathlib==0.21.1",
    "cloudpickle==3.1.1",
    "cnocr==2.2.3.2",
    "cnstd==1.2.5.2",
    "colorama==0.4.6",
    "coloredlogs==15.0.1",
    "colorful==0.5.6",
    "confection==0.1.5",
    "contourpy==1.3.2",
    "cycler==0.12.1",
    "cymem==2.0.11",
    "datasets==2.14.4",
    "defusedxml==0.7.1",
    "dill==0.3.7",
    "distlib==0.3.9",
    "evaluate==0.3.0",
    "exceptiongroup==1.3.0",
    "executing==2.2.0",
    "fastai==2.7.19",
    "fastapi==0.115.13",
    "fastcore==1.7.29",
    "fastdownload==0.0.7",
    "fastprogress==1.0.3",
    "filelock==3.18.0",
    "flatbuffers==25.2.10",
    "fonttools==4.58.4",
    "frozenlist==1.7.0",
    "fsspec==2025.5.1",
    "future==1.0.0",
    "gdown==5.2.0",
    "gluonts==0.13.9",
    "google-api-core==2.25.1",
    "google-auth==2.40.3",
    "googleapis-common-protos==1.70.0",
    "gpustat==1.1.1",
    "graphviz==0.21",
    "greenlet==3.2.3",
    "grpcio==1.49.1",
    "h11==0.16.0",
    "huggingface-hub==0.33.0",
    "humanfriendly==10.0",
    "hyperopt==0.2.7",
    "icecream==2.1.4",
    "idna==3.10",
    "imageio==2.37.0",
    "jinja2==3.1.6",
    "jinxed==1.3.0",
    "jmespath==1.0.1",
    "joblib==1.5.1",
    "jsonschema==4.17.3",
    "kiwisolver==1.4.8",
    "langcodes==3.5.0",
    "language-data==1.3.0",
    "lightgbm==3.3.5",
    "lightning-utilities==0.14.3",
    "llvmlite==0.44.0",
    "marisa-trie==1.2.1",
    "markdown==3.8",
    "markdown-it-py==3.0.0",
    "markupsafe==3.0.2",
    "matplotlib==3.10.3",
    "mdurl==0.1.2",
    "mlforecast==0.7.3",
    "model-index==0.1.11",
    "mpmath==1.3.0",
    "msgpack==1.1.1",
    "multidict==6.5.0",
    "multiprocess==0.70.15",
    "murmurhash==1.0.13",
    "narwhals==1.43.0",
    "networkx==3.4.2",
    "nlpaug==1.1.11",
    "nltk==3.9.1",
    "nptyping==2.4.1",
    "numba==0.61.2",
    "numpy==1.26.4",
    "nvidia-ml-py==12.575.51",
    "omegaconf==2.2.3",
    "onnx==1.17.0",
    "onnxruntime==1.15.1",
    "opencensus==0.11.4",
    "opencensus-context==0.1.3",
    "opencv-python==4.8.1.78",
    "opencv-python-headless==4.11.0.86",
    "opendatalab==0.0.10",
    "openmim==0.3.9",
    "openxlab==0.0.11",
    "ordered-set==4.1.0",
    "packaging==25.0",
    "pandas==1.5.3",
    "patsy==1.0.1",
    "pillow==9.5.0",
    "pip==25.1.1",
    "platformdirs==4.3.8",
    "plotly==6.1.2",
    "preshed==3.0.10",
    "prometheus-client==0.22.1",
    "propcache==0.3.2",
    "proto-plus==1.26.1",
    "protobuf==3.20.2",
    "psutil==5.9.8",
    "py-cpuinfo==9.0.0",
    "py-spy==0.4.0",
    "py4j==0.10.9.9",
    "pyarrow==20.0.0",
    "pyasn1==0.6.1",
    "pyasn1-modules==0.4.2",
    "pyclipper==1.3.0.post6",
    "pycryptodome==3.23.0",
    "pydantic==1.10.22",
    "pygments==2.19.1",
    "pymysql==1.0.2",
    "pyparsing==3.2.3",
    "pyqt5==5.15.10",
    "pyqt5-qt5==5.15.2",
    "pyqt5-sip==12.17.0",
    "pyreadline3==3.5.4",
    "pyrsistent==0.20.0",
    "pysocks==1.7.1",
    "pytesseract==0.3.10",
    "python-dateutil==2.9.0.post0",
    "pytorch-lightning==1.9.5",
    "pytorch-metric-learning==1.7.3",
    "pytz==2025.2",
    "pywavelets==1.8.0",
    "pywin32==310",
    "pyyaml==6.0.2",
    "qudida==0.0.4",
    "rapidocr-onnxruntime==1.3.25",
    "ray==2.3.1",
    "regex==2024.11.6",
    "requests==2.32.4",
    "responses==0.18.0",
    "rich==14.0.0",
    "rsa==4.9.1",
    "s3transfer==0.13.0",
    "safetensors==0.5.3",
    "scikit-image==0.19.3",
    "scikit-learn==1.2.2",
    "scipy==1.11.4",
    "seaborn==0.13.2",
    "sentencepiece==0.2.0",
    "seqeval==1.2.2",
    "setuptools==80.9.0",
    "shapely==2.1.1",
    "shellingham==1.5.4",
    "six==1.17.0",
    "smart-open==7.1.0",
    "sniffio==1.3.1",
    "soupsieve==2.7",
    "spacy==3.8.7",
    "spacy-legacy==3.0.12",
    "spacy-loggers==1.0.5",
    "sqlalchemy==1.4.44",
    "srsly==2.5.1",
    "starlette==0.46.2",
    "statsforecast==1.4.0",
    "statsmodels==0.14.4",
    "sympy==1.14.0",
    "tabulate==0.9.0",
    "tensorboard==2.19.0",
    "tensorboard-data-server==0.7.2",
    "tensorboardx==2.6.4",
    "text-unidecode==1.3",
    "thinc==8.3.4",
    "threadpoolctl==3.6.0",
    "tifffile==2025.5.10",
    "timm==0.9.16",
    "tokenizers==0.13.3",
    "toolz==0.12.1",
    "torch==1.13.1",
    "torchmetrics==0.11.4",
    "torchvision==0.14.1",
    "tqdm==4.67.1",
    "transformers==4.26.1",
    "typer==0.16.0",
    "typing-extensions==4.14.0",
    "ujson==5.10.0",
    "ultralytics==8.3.156",
    "ultralytics-thop==2.0.14",
    "unidecode==1.4.0",
    "urllib3==2.4.0",
    "uvicorn==0.22.0",
    "virtualenv==20.31.2",
    "wasabi==1.1.3",
    "wcwidth==0.2.13",
    "weasel==0.4.1",
    "werkzeug==3.1.3",
    "wheel==0.45.1",
    "window-ops==0.0.15",
    "wrapt==1.17.2",
    "xgboost==1.7.6",
    "xxhash==3.5.0",
    "yarl==1.20.1",
]
