[build-system]
requires = ["setuptools>=81.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "drill_map_ai"
version = "0.1.0"
description = "Drill Map AI 模組"
authors = [
    { name="Dante", email="Dante_Chen@aseglobal.com" }
]
dependencies = [
    "numpy",
    "pandas",
    "torch",
    "cnocr",
    "opencv-python",
    "autogluon.tabular",
    "scipy",
    "Pillow"
]
requires-python = ">=3.10.13"